version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
        - post_db
        - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${UI_OUT_PORT}:${UI_IN_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
