kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 1Swctw9R75gwdvYkuAyHWR6g+Mb57BBXBgC0nkge00k=
      - identity: {}
